### PR TITLE
Update logo

### LINKED ISSUE #31: Logo
Image

### PR DESCRIPTION
**Pull request by faissaloux**
Resolves #31

image
image
image
image

### CODE REVIEW

**Comment by ismaail** [comment]
I pulled this PR & I get this error

image

---

FIX: change the first line to:

```blade
@php echo '<?xml version="1.0" encoding="utf-8"?>' @endphp
```

**Comment by faissaloux** [comment]
@ismaail Can you specify which route? What you did exactly to reproduce!

**Comment by faissaloux** [comment]
@Zakarialabib This is not yet ready, we still need the [social card](https://github.com/laravelmorocco/laravelmaroc.com/blob/main/public/images/socialcard.png)

**Comment by faissaloux** [comment]
@ismaail It's fixed, can you check again?

**Comment by ismaail** [comment]
@faissaloux yes, removing this two lines fixes the issue.

**Review by ismaail — APPROVED** [review]

**Review by Zakarialabib — APPROVED** [review]

**Pull request merged**
